name: cbj_hub
description: Easy to use open source Hub to control your smart devices from one app.
version: 1.3.0+6
homepage: https://cybearjinni.com
publish_to: none

environment:
  sdk: ^2.18.2

dependencies:
  # Contains utility classes in the style of dart:async to work with asynchronous computations.
  async: ^2.11.0
  # Package to create, convert, alter, and compare colors in a variety of colorspaces.
  color: ^3.0.0
  # Compute function made available for all non-Flutter Dart programs
  compute: ^1.0.2
  # Collection of cyclic redundancy check (CRC) routines as Dart converters.
  crclib: ^3.0.0
  # Functional programming thingies, let you use multiple return types
  dart_ewelink_api: ^0.0.6
  dartz: ^0.10.1
  # Allow returning more than one type of object
  equatable: ^2.0.5
  # Annotations for freezed
  freezed_annotation: ^2.2.0
  # For the injection, allow accessing an object from anywhere in an App
  get_it: ^7.2.0
  # High performance, open-source universal RPC framework
  grpc: ^3.1.0
  # Lightweight and blazing fast key-value database
  hive: ^2.2.3
  # Library for making HTTP requests.
  http: ^0.13.5
  # Philips Hue API
  hue_dart:
    git:
      url: 'https://github.com/guyluz11/hue_dart.git'
  # Convenient code generator for get_it
  injectable: ^2.1.0
  # Utility library that checks for an Active Internet connection
  internet_connection_checker: ^1.0.0+1
  # Extremely fast, easy to use, and fully async NoSQL database.
#  isar: ^3.0.5
  # Defines the annotations used by json_serializable to create code for JSON serialization and deserialization.
  json_annotation: ^4.8.0
  # Dart Build System builders for handling JSON.
  json_serializable: ^6.6.1
  # Port of Kotlin's Kotlin Standard library for Dart/Flutter projects
  kt_dart: ^1.1.0
  # Implementation of the LIFX HTTP API
  lifx_http_api: ^0.0.16
  # Small, easy to use and extensible logger which prints beautiful logs.
  logger: ^1.3.0
  # A server and browser based MQTT client for Dart.
  mi_iot_token: ^1.0.0
  mqtt_client: ^9.8.1
  # Service discovery over multicast DNS (mDNS), Bonjour, and Avahi.
  multicast_dns: ^0.3.2+3
  # Helps you discover open ports, devices on subnet and more.
  network_tools: ^3.2.1
  # Provides runtime support for a Dart implementation of protobufs.
  protobuf: ^2.1.0
  # Python Environment Manager and Executor for dart and flutter
  python_shell:
    git: 'https://github.com/guyluz11/python_shell.dart.git'
  # Extends the capabilities of Dart Streams and StreamControllers.
  rxdart: ^0.27.7
  # Simple, fast generation of RFC4122 UUIDs.
  uuid: ^3.0.7
  # Dart library for controlling Yeelight products over LAN.
  yeedart: ^0.3.2

dev_dependencies:
  # A build system for Dart code generation and modular compilation.
  build_runner:

  # A generator for injectable library
  # Code generator for unions/pattern-matching/copy.
  freezed: ^2.3.2
  # Automatically generates Hive TypeAdapters to store any class
  hive_generator: ^2.0.0
  # Injectable is a convenient code generator for get_it.
  injectable_generator: ^2.1.4
  # Code generator for the Isar Database. Finds classes annotated with @Collection.
#  isar_generator: ^3.0.5
  # Collection of lint rules for Dart and Flutter projects
  lint: ^2.0.1
  # Library for mocks
  mockito: ^5.3.2
  # A full featured library for writing and running Dart tests across platforms.
  test: ^1.24.0
