# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart CI

on:
  pull_request:
    branches: [ main, dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603

      - name: Install dependencies
        run: dart pub get

      - name: generate_all_files
        run: dart run build_runner build --delete-conflicting-outputs

      # Verify the use of 'dart format' on each commit.
      - name: Perform formatting
        run: find . -name "*.dart" ! -path '*/gen/*' | tr '\n' ' ' | xargs dart format .

      # Consider passing '--fatal-infos' for slightly stricter analysis.
      - name: Analyze project source
        run: dart analyze

      # Your project will need to have tests in test/ and a dependency on
      # package:test for this step to succeed.
      - name: Run tests
        run: dart test

      # Perform the commit at the end to make sure tests above don't fail
      - name: Commit formatting changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.SECRET }}@github.com/${{ github.repository }}
          git add .
          git diff-index --quiet HEAD || (git commit -m 'Automatic formatting' && git push)
          